site_name: Aceleración de la integración de Monte Carlo

theme:
  name: material
  language: es

plugins:
  - search
  - mkdoxy:
      projects:
        cpp:
          src-dirs: "src include"
          doxy-cfg:
            FILE_PATTERNS: "*.cpp *.h*"
            RECURSIVE: True

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Tutoriales:
      - Calculo de integral con MC en memoria compartida: ejemMCshare.md
      - Calculo de integral con MC en memoria distribuida: ejemDis.md
  - Referencias: 
      - MC en memoria compartida: cpp/classMC.md
      - MC en memoria distribuida: cpp/classMonteCarloMPI.md
